browser=CHROME
headless=true
explicitWait=10

grid.url=http://selenium-hub:4444

# Service base URLs ? add more services as needed
hcm.baseUrl=https://uat_mcdp_hcm.omfysgroup.com/login
#crm.baseUrl=https://qa-crm.omfysgroup.com/login
platform.baseUrl=https://uat_mcdp_hcm.omfysgroup.com/login