browser=EDGE
headless=true
explicitWait=5
grid.url=http://selenium-hub:4444

hcm.baseUrl=https://uat_mcdp_hcm.omfysgroup.com/login
#crm.baseUrl=https://uat-crm.omfysgroup.com/login
platform.baseUrl=https://uat_mcdp_hcm.omfysgroup.com/login