package com.kavish.core.utils;

import com.kavish.core.config.ConfigFactory;
import com.kavish.core.config.FrameworkConfig;

import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

public final class AllureEnvironmentWriter {
 private AllureEnvironmentWriter() {}

 public static void write() {
 FrameworkConfig cfg = ConfigFactory.getConfig();
 Path resultsDir = Path.of(System.getProperty("allure.results.directory", "target/allure-results"));
 try {
 Files.createDirectories(resultsDir);
 Properties props = new Properties();
 props.setProperty("env", cfg.env());
 props.setProperty("service", cfg.service());
 props.setProperty("browser", String.valueOf(cfg.browser()));
 props.setProperty("headless", String.valueOf(cfg.headless()));
 props.setProperty("grid.url", String.valueOf(cfg.gridUrl()));
 props.setProperty("base.url", safeBaseUrl(cfg));
 props.setProperty("java.version", System.getProperty("java.version"));
 props.setProperty("os.name", System.getProperty("os.name"));
 props.setProperty("os.arch", System.getProperty("os.arch"));
 try (Writer writer = Files.newBufferedWriter(resultsDir.resolve("environment.properties"))) {
 props.store(writer, "Generated by TestListener.onStart");
 }
 } catch (IOException e) {
 throw new RuntimeException("Failed to write Allure environment.properties", e);
 }
 }

 private static String safeBaseUrl(FrameworkConfig cfg) {
 try {
 return cfg.baseUrl();
 } catch (Exception ex) {
 return "unavailable";
 }
 }
}
